[package]
name = "reveldb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "3.0.1"
integer-encoding = "4.0.0"
tempdir = "0.3.7"

[[bin]]
name = "reveldb"
path = "src/main.rs"
